### ISSUE TITLE
setValueSelected() doesn't change the value of the seekbar

### ISSUE THREAD

**Issue by anass05** [fairytale110/BezierSeekBar#1]
i have a button that changes the value of the seekbar to a random number each time i click on it, 
but that doesn't effect the seekbar, when i added invalidate() on the seekbar it changes the value but the indicator doesn't move to the correct position. 

`final BezierSeekBar brightnessSeekBar;
        brightnessSeekBar = findViewById(R.id.xx);
        Button bb = findViewById(R.id.bb);
        bb.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                brightnessSeekBar.setValueSelected(new Random().nextInt((300) + 1) -150);
                Log.d("TAG", "onClick: "+brightnessSeekBar.getValueSelected());
                brightnessSeekBar.invalidate();
            }
        });`

thank you.

**Comment by fairytale110** [comment]
Hold on，let me check my code

**Comment by fairytale110** [comment]
Fixed at 1.0.3 ,
